### ISSUE TITLE
Jenkins Template enhancements

### ISSUE THREAD

**Issue by bzon** [clerixmaxime/AdopOnOpenshift#8]
- Readiness and Liveliness probe should `http GET /robots.txt` instead of just port 8080. This is how to easily check Jenkins health from http.  

```yaml
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /robots.txt
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /robots.txt
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 240
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
```

- If you tried running jenkins with an NFS or host path Persistent Volume, you will encounter permission errors since it does a lot of permission changes on its entrypoint.sh script. We resolved this by making jenkins  `runAsUser: 0`. This is tested using Accenture's latest adop-jenkins docker image.  

```yaml
        securityContext:
          runAsUser: 0
```

I got this __runAsUser__ reference from Kubernetes official Jenkins Helm deployment template  https://github.com/kubernetes/charts/blob/master/stable/jenkins/templates/jenkins-master-deployment.yaml.  It is maybe because of the same reason.
